# Generated by Django 3.0.4 on 2020-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('AuthCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=50)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PicRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PicID', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SrRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('DetailDescrip', models.CharField(max_length=400)),
                ('ugency', models.CharField(max_length=20)),
                ('DueDate', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('CreateDate', models.DateTimeField()),
                ('ModifyDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UerInfo',
            fields=[
                ('CompanyAuthCode', models.CharField(max_length=50)),
                ('NickName', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=50)),
                ('PhoneNum', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
